name: Packaging

on: 
  - push

jobs:
  run_test:
    name: Check Tests
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-python@v4.0.0
            with:
              python-version: "3.10"
        - name: Test classes
          run: py -m pytest